from .commonErrorCode import CommonErrorCode

OK = CommonErrorCode("200", "OK")
CREATED = CommonErrorCode("201", "Created")
ACCEPTED = CommonErrorCode("202", "Accepted")
NON_AUTHORITATIVE_INFORMATION = CommonErrorCode("203", "Non-Authoritative Information")
NO_CONTENT = CommonErrorCode("204", "No Content")
RESET_CONTENT = CommonErrorCode("205", "Reset Content")
PARTIAL_CONTENT = CommonErrorCode("206", "Partial Content")
MULTI_STATUS = CommonErrorCode("207", "Multi-Status")
ALREADY_REPORTED = CommonErrorCode("208", "Already Reported")
IM_USED = CommonErrorCode("226", "IM Used")

MULTIPLE_CHOICES = CommonErrorCode("300", "Multiple Choices")
MOVED_PERMANENTLY = CommonErrorCode("301", "Moved Permanently")
FOUND = CommonErrorCode("302", "Found")
MOVED_TEMPORARILY = CommonErrorCode("302", "Moved Temporarily")
SEE_OTHER = CommonErrorCode("303", "See Other")
NOT_MODIFIED = CommonErrorCode("304", "Not Modified")
USE_PROXY = CommonErrorCode("305", "Use Proxy")
TEMPORARY_REDIRECT = CommonErrorCode("307", "Temporary Redirect")
PERMANENT_REDIRECT = CommonErrorCode("308", "Permanent Redirect")

BAD_REQUEST = CommonErrorCode("400", "Bad Request")
UNAUTHORIZED = CommonErrorCode("401", "Unauthorized")
PAYMENT_REQUIRED = CommonErrorCode("402", "Payment Required")
FORBIDDEN = CommonErrorCode("403", "Forbidden")
NOT_FOUND = CommonErrorCode("404", "Not Found")
METHOD_NOT_ALLOWED = CommonErrorCode("405", "Method Not Allowed")
NOT_ACCEPTABLE = CommonErrorCode("406", "Not Acceptable")
PROXY_AUTHENTICATION_REQUIRED = CommonErrorCode("407", "Proxy Authentication Required")
REQUEST_TIMEOUT = CommonErrorCode("408", "Request Timeout")
CONFLICT = CommonErrorCode("409", "Conflict")
GONE = CommonErrorCode("410", "Gone")
LENGTH_REQUIRED = CommonErrorCode("411", "Length Required")
PRECONDITION_FAILED = CommonErrorCode("412", "Precondition Failed")
PAYLOAD_TOO_LARGE = CommonErrorCode("413", "Payload Too Large")
REQUEST_ENTITY_TOO_LARGE = CommonErrorCode("413", "Request Entity Too Large")
URI_TOO_LONG = CommonErrorCode("414", "URI Too Long")
REQUEST_URI_TOO_LONG = CommonErrorCode("414", "Request-URI Too Long")
UNSUPPORTED_MEDIA_TYPE = CommonErrorCode("415", "Unsupported Media Type")
REQUESTED_RANGE_NOT_SATISFIABLE = CommonErrorCode("416", "Requested range not satisfiable")
EXPECTATION_FAILED = CommonErrorCode("417", "Expectation Failed")
I_AM_A_TEAPOT = CommonErrorCode("418", "I'm a teapot")
INSUFFICIENT_SPACE_ON_RESOURCE = CommonErrorCode("419", "Insufficient Space On Resource")
METHOD_FAILURE = CommonErrorCode("420", "Method Failure")
DESTINATION_LOCKED = CommonErrorCode("421", "Destination Locked")
UNPROCESSABLE_ENTITY = CommonErrorCode("422", "Unprocessable Entity")
LOCKED = CommonErrorCode("423", "Locked")
FAILED_DEPENDENCY = CommonErrorCode("424", "Failed Dependency")
TOO_EARLY = CommonErrorCode("425", "Too Early")
UPGRADE_REQUIRED = CommonErrorCode("426", "Upgrade Required")
PRECONDITION_REQUIRED = CommonErrorCode("428", "Precondition Required")
TOO_MANY_REQUESTS = CommonErrorCode("429", "Too Many Requests")
REQUEST_HEADER_FIELDS_TOO_LARGE = CommonErrorCode("431", "Request Header Fields Too Large")
UNAVAILABLE_FOR_LEGAL_REASONS = CommonErrorCode("451", "Unavailable For Legal Reasons")

INTERNAL_SERVER_ERROR = CommonErrorCode("500", "Internal Server Error")
NOT_IMPLEMENTED = CommonErrorCode("501", "Not Implemented")
BAD_GATEWAY = CommonErrorCode("502", "Bad Gateway")
SERVICE_UNAVAILABLE = CommonErrorCode("503", "Service Unavailable")
GATEWAY_TIMEOUT = CommonErrorCode("504", "Gateway Timeout")
HTTP_VERSION_NOT_SUPPORTED = CommonErrorCode("505", "HTTP Version not supported")
VARIANT_ALSO_NEGOTIATES = CommonErrorCode("506", "Variant Also Negotiates")
INSUFFICIENT_STORAGE = CommonErrorCode("507", "Insufficient Storage")
LOOP_DETECTED = CommonErrorCode("508", "Loop Detected")
BANDWIDTH_LIMIT_EXCEEDED = CommonErrorCode("509", "Bandwidth Limit Exceeded")
NOT_EXTENDED = CommonErrorCode("510", "Not Extended")
NETWORK_AUTHENTICATION_REQUIRED = CommonErrorCode("511", "Network Authentication Required")

UNKNOWN_EXCEPTION = CommonErrorCode("600", "Unknown Exception")

INVALID_PARAM = CommonErrorCode("10000", "Invalid Param")
DB_EXCEPTION = CommonErrorCode("10001", "Db Exception")
NULL_POINTER = CommonErrorCode("10002", "Null Pointer Exception")
CURRENT_LIMITING = CommonErrorCode("10003", "Current Limiting")
SERIALIZATION_FAIL = CommonErrorCode("10004", "Serialization Fail")
DESERIALIZATION_FAIL = CommonErrorCode("10005", "Deserialization Fail")
